language: node_js
node_js:
  - lts/*
  - node
before_install:
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
script:
  - npm i -g lsc nsp codecov
  - nsp check
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codecov
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
