language: node_js
node_js:
  - 8.9.0
before_install:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
  - npm install -g lsc nsp
script:
  - nsp check
  - npm test
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
